data-in:
  portfolio-value: 106.50 # for proportions, use 1
  price-data: live # live for auto data (takes longer)
  index-col: Date
  data-col: Close
  views-file: views/views.txt
model:
  type: black-litterman # markowitz/black-litterman
  short: no # yes/no
  penalty: none # none/l1/l2
  penalty-weight: 0 # [0, 1]
data-out:
  plot: no # yes/no
